apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j5gehnq25-nodejs 
  janus-idp.io/tekton: j5gehnq25-nodejs
  backstage.io/kubernetes-id: j5gehnq25-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5gehnq25-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml